version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels: ["deps", "github-actions"]
    commit-message:
      prefix: "deps(actions)"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["deps", "npm"]
    commit-message:
      prefix: "deps(npm)"
      
  - package-ecosystem: "composer"
    directory: "/" 
    schedule:
      interval: "daily"
